name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Cypress (build, start, test)
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          browser: electron
        env:
          GITHUB_USERNAME: your-github-username
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
